### ISSUE TITLE
Password flow

### ISSUE THREAD

**Issue by tobidelius** [rocketmade/rockoauth#7]
Is there an endpoint example for the password flow?

**Comment by danielevans** [comment]
The example endpoint in the README is what you are looking for. The critical part to enabling password grants is configuring the `handle_passwords` block in your initializers/configs.

The Endpoint: https://github.com/rocketmade/rockoauth#oauth-request-endpoint

An example password handler block: https://github.com/rocketmade/rockoauth#using-password-credentials

**Comment by tobidelius** [comment]
Got it. The example really need some love. I'll see if I have some time over the next few days.

**Comment by tobidelius** [comment]
Hmm I really can't make the example work with the password flow. Postman is saying "Could not get any response". Any ideas?

**Comment by danielevans** [comment]
The examples do need some love :)

Can you give me an example of what you are trying that isn't working?

**Comment by danielevans** [comment]
@sandelius were you able to get things worked out?
